cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    seongmoon:
      name: seongmoon
      password: $2b$12$DSqn.qveDiWKjP.Nmw44n.lCYuVhhueyGP0N7wrUuOUZjt7XeuZju
    "\uC131\uBB38":
      name: "\uC131\uBB38"
      password: $2b$12$MsSCnkwFftwdHelZElovUOzs74jeH8hHdLWaqr1aaTB5BDg3a0TjS
preauthorized:
  emails:
  - melsby@gmail.com
